---
title: "B5"
author: "filippo"
date: "4 April 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Esercizio 5.

Sia Y una v.c. di Poisson di parametro $\lambda$. Sia dato un campione bernoulliano $(Y_1,...,Y_n), n > 3$ . Si considerino i seguenti stimatori di $\lambda$:

$T_1 = \frac{\sum^{n-2}_{i=1}{Y_i}}{n-1}+\frac{Y_n}{n-1}$  
$T_2 = \frac{Y_1+(n-2)Y_n}{n-1}$  

**(a) Calcolare le distorsioni dei due stimatori proposti.**   

Ricordiamo che una v.c. di Poisson ha la seguente caratteristica:  
$E(Y) = \lambda$  

$bias(T_1) = E(T_1) - \lambda$  
$E(T_1) = \frac{(n-2)E(Y)}{n-1}+\frac{E(Y)}{n-1} = \frac{(n-2)\lambda}{n-1}+\frac{\lambda}{n-1}$ $=\frac{(n-2)\lambda+\lambda}{n-1} = \frac{\lambda(1+n-2)}{n-1} = \frac{\lambda(n-1)}{n-1} = \lambda$  
$T_1$ è quindi non distorto

$bias(T_2) = E(T_2) - \lambda$  
$E(T_2) = \frac{E(Y)+(n-2)E(Y)}{n-1} = \frac{\lambda+(n-2)\lambda}{n-1}$  
$=\frac{\lambda(1+n-2)}{n-1}=\frac{\lambda(n-1)}{n-1} = \lambda$
Anche $T_2$ è quindi non distorto

**(b) Calcolare le varianze dei due stimatori.**  
Ricordiamo che una v.c. di Poisson ha la seguente caratteristica:  
$Var(Y) = \lambda$

$Var(T_1) = Var(\frac{\sum^{n-2}_{i=1}{Y_i}}{n-1})+Var(\frac{Y_n}{n-1})$  
$= \frac{\sum^{n-2}_{i=1}{Var(Y_i)}}{(n-1)^2}+\frac{Var(Y_n)}{(n-1)^2}$  
$= \frac{(n-2){Var(Y)}}{(n-1)^2}+\frac{Var(Y)}{(n-1)^2} = \frac{(n-2)\lambda+\lambda}{(n-1)^2}$  
$= \frac{\lambda(1+n-2)}{(n-1)^2}= \frac{\lambda(n-1)}{(n-1)^2}$  
$= \frac{\lambda}{n-1}$   

$Var(T_2) = \frac{Var(Y)+(n-2)^2Var(Y)}{(n-1)^2}= \frac{\lambda+(n-2)^2\lambda}{(n-1)^2}$  
$=\frac{\lambda(1+(n-2)^2)}{(n-1)^2}$
$=\frac{\lambda(n^2-4n+5)}{n^2-2n+1}$

**(c) Calcolare gli errori quadratici medi.**  
$Mse(Y)=Var(Y)+Bias(Y)^2$  

Entrambi gli stimatori sono non distorti, quindi otterremo un Mse coincidente con la Varianza  

$Mse(T_1)=Var(T_1)+Bias(T_1)^2 = \frac{\lambda}{n-1}$  
$Mse(T_2)=Var(T_2)+Bias(T_2)^2 = \frac{\lambda(n^2-4n+5)}{n^2-2n+1}$


**(d) Quale dei due stimatori risulta preferibile ?**

